
import os
import json

from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker, declarative_base

from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.foundation_models.utils.enums import DecodingMethods
from ibm_watsonx_ai import Credentials


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

WATSONX_API_KEY = os.getenv("WATSONX_API_KEY")
WATSONX_PROJECT_ID = os.getenv("WATSONX_PROJECT_ID")
WATSONX_URL = os.getenv("WATSONX_URL")


# ============================================================
# CHECK WATSONX CONFIGURATION
# ============================================================

if not WATSONX_API_KEY:
    raise RuntimeError(
        "WATSONX_API_KEY is missing from the .env file."
    )

if not WATSONX_PROJECT_ID:
    raise RuntimeError(
        "WATSONX_PROJECT_ID is missing from the .env file."
    )

if not WATSONX_URL:
    raise RuntimeError(
        "WATSONX_URL is missing from the .env file."
    )


# ============================================================
# WATSONX CREDENTIALS
# ============================================================

credentials = Credentials(
    api_key=WATSONX_API_KEY,
    url=WATSONX_URL
)


# ============================================================
# WATSONX MODEL
# ============================================================

model = ModelInference(
     model_id="ibm/granite-4-h-small",
    credentials=credentials,
    params={
        "decoding_method": DecodingMethods.GREEDY,
        "max_new_tokens": 200
    },
    project_id=WATSONX_PROJECT_ID
)


# ============================================================
# AI MODEL FUNCTION
# ============================================================

def call_model(prompt: str):

    try:

        response = model.generate_text(
            prompt=prompt
        )

        if isinstance(response, str):
            return response

        if isinstance(response, list):

            if len(response) > 0:
                return str(response[0])

        if isinstance(response, dict):

            if "generated_text" in response:
                return response["generated_text"]

            if "results" in response:

                results = response["results"]

                if results:

                    return results[0].get(
                        "generated_text",
                        "No response generated."
                    )

        return "No response generated by the AI model."

    except Exception as e:

        raise HTTPException(
            status_code=503,
            detail=f"AI model call failed: {str(e)}"
        )


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

DATABASE_URL = "sqlite:///./app.db"

engine = create_engine(
    DATABASE_URL,
    connect_args={
        "check_same_thread": False
    }
)

SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    autocommit=False
)

Base = declarative_base()


# ============================================================
# DATABASE TABLE
# ============================================================

class Feedback(Base):

    __tablename__ = "feedback"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    user_id = Column(
        String,
        nullable=False
    )

    message = Column(
        String,
        nullable=False
    )


# Create table automatically
Base.metadata.create_all(
    bind=engine
)


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Smart City Assistant API",
    description="AI-powered Smart City Assistant Backend",
    version="1.0.0"
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)


# ============================================================
# DATABASE DEPENDENCY
# ============================================================

def get_db():

    db = SessionLocal()

    try:
        yield db

    finally:
        db.close()


# ============================================================
# REQUEST MODELS
# ============================================================

class Prompt(BaseModel):
    prompt: str


class TextInput(BaseModel):
    text: str


class FeedbackModel(BaseModel):
    user_id: str
    message: str


class PolicyRequest(BaseModel):
    query: str
    policy_text: str


class AnomalyPayload(BaseModel):
    data: list[float]


# ============================================================
# ROOT
# ============================================================

@app.get("/")
def root():

    return {
        "message": "Smart City Assistant Backend Running",
        "status": "online"
    }


# ============================================================
# CHAT
# ============================================================

@app.post("/chat")
def chat_endpoint(payload: Prompt):

    prompt = payload.prompt.strip()

    if not prompt:

        raise HTTPException(
            status_code=400,
            detail="Prompt cannot be empty."
        )

    return {
        "response": call_model(prompt)
    }


# ============================================================
# TEXT CORRECTION
# ============================================================

@app.post("/text-correction")
def correct_text(payload: TextInput):

    text = payload.text.strip()

    if not text:

        raise HTTPException(
            status_code=400,
            detail="Text cannot be empty."
        )

    prompt = f"""
Please correct the grammar and spelling
in the following text.

Return only the corrected version.

Text:
{text}
"""

    return {
        "corrected_text": call_model(prompt)
    }


# ============================================================
# ECO TIPS
# ============================================================

@app.get("/eco-tips")
def eco_tips():

    prompt = """
Give one unique and practical eco-friendly
tip for urban life.

Include:
1. An emoji
2. The eco-friendly tip
3. A short explanation

Keep the response concise.
"""

    return {
        "tip": call_model(prompt)
    }


# ============================================================
# KPI FORECAST
# ============================================================

@app.post("/forecast-kpi")
def forecast_kpi(payload: AnomalyPayload):

    if not payload.data:

        raise HTTPException(
            status_code=400,
            detail="Historical data cannot be empty."
        )

    prompt = f"""
You are a data forecasting assistant.

Historical data:
{payload.data}

Forecast the next 3 values.

Return ONLY a JSON list.

Example:
[21, 24, 27]
"""

    raw_response = call_model(prompt)

    forecast = []

    try:

        cleaned = raw_response.strip()

        if cleaned.startswith("```"):

            cleaned = cleaned.replace(
                "```json",
                ""
            )

            cleaned = cleaned.replace(
                "```",
                ""
            )

            cleaned = cleaned.strip()

        forecast = json.loads(cleaned)

        if not isinstance(forecast, list):

            forecast = []

    except Exception:

        forecast = []

    return {
        "forecast_next_3_periods": forecast,
        "raw_response": raw_response
    }


# ============================================================
# SUBMIT FEEDBACK
# ============================================================

@app.post("/submit-feedback")
def submit_feedback(
    fb: FeedbackModel,
    db=Depends(get_db)
):

    user_id = fb.user_id.strip()
    message = fb.message.strip()

    if not user_id:

        raise HTTPException(
            status_code=400,
            detail="User name cannot be empty."
        )

    if not message:

        raise HTTPException(
            status_code=400,
            detail="Feedback cannot be empty."
        )

    entry = Feedback(
        user_id=user_id,
        message=message
    )

    db.add(entry)
    db.commit()
    db.refresh(entry)

    return {
        "message": "Feedback submitted successfully"
    }


# ============================================================
# GET FEEDBACK
# ============================================================

@app.get("/feedback")
def get_feedback(
    db=Depends(get_db)
):

    items = db.query(
        Feedback
    ).all()

    return [
        {
            "user_id": item.user_id,
            "message": item.message
        }
        for item in items
    ]


# ============================================================
# POLICY SUMMARY
# ============================================================

@app.post("/policy-summary")
def policy_summary(
    req: PolicyRequest
):

    query = req.query.strip()
    policy_text = req.policy_text.strip()

    if not query:

        raise HTTPException(
            status_code=400,
            detail="Query cannot be empty."
        )

    if not policy_text:

        raise HTTPException(
            status_code=400,
            detail="Policy text cannot be empty."
        )

    prompt = f"""
Summarize the following city policy.

Focus specifically on:
{query}

Policy:
{policy_text}

Give a clear and concise summary.
"""

    return {
        "summary": call_model(prompt)
    }


# ============================================================
# WEATHER
# ============================================================

@app.get("/weather")
def weather(city: str):

    city = city.strip()

    if not city:

        raise HTTPException(
            status_code=400,
            detail="City name cannot be empty."
        )

    prompt = f"""
Give weather information for {city}.

Include:
- Temperature
- Weather condition
- Suitable emoji

Keep the answer short.
"""

    return {
        "weather": {
            "description": call_model(prompt)
        }
    }


# ============================================================
# CITY UPDATES
# ============================================================

@app.get("/updates")
def city_updates(city: str):

    city = city.strip()

    if not city:

        raise HTTPException(
            status_code=400,
            detail="City name cannot be empty."
        )

    prompt = f"""
Give the latest city-related updates about {city}.

Include:
- Local happenings
- IT industry news
- General city developments

Return JSON in this format:

{{
    "description": "City updates",
    "temp": 31
}}
"""

    try:

        raw_response = call_model(prompt)

        try:

            cleaned = raw_response.strip()

            if cleaned.startswith("```"):

                cleaned = cleaned.replace(
                    "```json",
                    ""
                )

                cleaned = cleaned.replace(
                    "```",
                    ""
                )

                cleaned = cleaned.strip()

            parsed = json.loads(cleaned)

        except json.JSONDecodeError:

            parsed = {
                "description": raw_response,
                "temp": None
            }

        return {
            "updates": parsed
        }

    except HTTPException:

        raise

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=f"AI error: {str(e)}"
        )
